// currently not using this. Maybe in the future

import { extendTheme } from '@chakra-ui/react';

export const iListTheme = extendTheme({
  colors: {
    codeLife: {
      bgDark: '#4FD1C5',
      bgLight: 'teal',
      colorDark: '#F7FAFC',
      colorLight: '#F7FAFC',
      bgIconDark: '#4FD1C5',
      bgIconLight: 'teal',
      colorIconDark: '#F7FAFC',
      colorIconLight: '#F7FAFC',
      strikeLineDark: 'lightgreen',
      strikeLineLight: 'black',
      strikeTextDark: 'red',
      strikeTextLight: 'red',
      addedDark: '#F7FAFC',
      addedLight: 'teal',
      colorItemDark: '#4FD1C5',
      colorItemLight: '#4A5568',
      bgItemDark: '#2D3748',
      bgItemLight: '#E2E8F0',
      checkSchemeDark: 'green',
      checkSchemeLight: 'red',
      deleteIconDark: '#48BB78',
      deleteIconLight: '#48BB78',
      deleteOutlineDark: 'red',
      deleteOutlineLight: 'red',
    },
    passion: {
      bgDark: '#FF69B4',
      bgLight: '#FF69B4',
      colorDark: '#F7FAFC',
      colorLight: '#F7FAFC',
      bgIconDark: '#FF69B4',
      bgIconLight: '#FFC0CB',
      colorIconDark: 'red',
      colorIconLight: 'black',
      strikeLineDark: '#F7FAFC',
      strikeLineLight: 'red',
      strikeTextDark: 'red',
      strikeTextLight: 'red',
      addedDark: '#FFC0CB',
      addedLight: '#718096',
      colorItemDark: '#F7FAFC',
      colorItemLight: 'black',
      bgItemDark: '#2D3748',
      bgItemLight: '#FFF5F5',
      checkSchemeDark: 'pink',
      checkSchemeLight: 'pink',
      deleteIconDark: '#FFC0CB',
      deleteIconLight: '#FF69B4',
      deleteOutlineDark: 'red',
      deleteOutlineLight: 'red',
    },
    woodlands: {
      bgDark: '#32CD32',
      bgLight: '#4CBB17',
      colorDark: '#F7FAFC',
      colorLight: '#F7FAFC',
      bgIconDark: 'green',
      bgIconLight: '#808000',
      colorIconDark: 'black',
      colorIconLight: '#F7FAFC',
      strikeLineDark: '#F7FAFC',
      strikeLineLight: 'red',
      strikeTextDark: 'orange',
      strikeTextLight: '#808000',
      addedDark: '#32CD32',
      addedLight: 'green',
      colorItemDark: '#F7FAFC',
      colorItemLight: 'black',
      bgItemDark: 'rgb(26, 45, 44)',
      bgItemLight: '#FAF9F6',
      checkSchemeDark: 'yellow',
      checkSchemeLight: 'yellow',
      deleteIconDark: '#32CD32',
      deleteIconLight: 'green',
      deleteOutlineDark: '#32CD32',
      deleteOutlineLight: 'green',
    },
    ocean: {
      bgDark: 'cyan',
      bgLight: 'rgb(0, 220, 255)',
      colorDark: '#191970',
      colorLight: '#00008B',
      bgIconDark: 'blue',
      bgIconLight: '#40E0D0',
      colorIconDark: '#F7FAFC',
      colorIconLight: 'blue',
      strikeLineDark: 'orange',
      strikeLineLight: 'black',
      strikeTextDark: 'blue',
      strikeTextLight: 'blue',
      addedDark: 'blue',
      addedLight: 'blue',
      colorItemDark: '#F7FAFC',
      colorItemLight: 'black',
      bgItemDark: 'rgb(26, 32, 70)',
      bgItemLight: 'rgb(230, 255, 255)',
      checkSchemeDark: 'cyan',
      checkSchemeLight: 'cyan',
      deleteIconDark: 'cyan',
      deleteIconLight: 'blue',
      deleteOutlineDark: 'blue',
      deleteOutlineLight: 'orange',
    },
    harvest: {
      bgDark: 'orange',
      bgLight: 'orange',
      colorDark: 'orange',
      colorLight: 'orange',
      bgIconDark: 'orange',
      bgIconLight: 'orange',
      colorIconDark: 'orange',
      colorIconLight: 'orange',
      strikeLineDark: 'orange',
      strikeLineLight: 'orange',
      strikeTextDark: 'orange',
      strikeTextLight: 'orange',
      addedDark: 'orange',
      addedLight: 'orange',
      colorItemDark: 'orange',
      colorItemLight: 'orange',
      bgItemDark: 'orange',
      bgItemLight: 'orange',
      checkSchemeDark: 'orange',
      checkSchemeLight: 'orange',
      deleteIconDark: 'orange',
      deleteIconLight: 'orange',
      deleteOutlineDark: 'orange',
      deleteOutlineLight: 'orange',
    },
    royal: {
      bgDark: 'purple',
      bgLight: 'purple',
      colorDark: 'purple',
      colorLight: 'purple',
      bgIconDark: 'purple',
      bgIconLight: 'purple',
      colorIconDark: 'purple',
      colorIconLight: 'purple',
      strikeLineDark: 'purple',
      strikeLineLight: 'purple',
      strikeTextDark: 'purple',
      strikeTextLight: 'purple',
      addedDark: 'purple',
      addedLight: 'purple',
      colorItemDark: 'purple',
      colorItemLight: 'purple',
      bgItemDark: 'purple',
      bgItemLight: 'purple',
      checkSchemeDark: 'purple',
      checkSchemeLight: 'purple',
      deleteIconDark: 'purple',
      deleteIconLight: 'purple',
      deleteOutlineDark: 'purple',
      deleteOutlineLight: 'purple',
    },
  },
});
